version: '3'

vars:
  COMPOSE_DIR: deployments
  WEB_DIR: web
  DATABASE_URL: postgresql://openseer:openseer@localhost:5432/openseer

tasks:
  up:
    desc: Start all application services
    dir: '{{.COMPOSE_DIR}}'
    cmds:
      - docker compose --profile app up -d --wait

  down:
    desc: Stop all application services
    dir: '{{.COMPOSE_DIR}}'
    cmds:
      - docker compose --profile app down --remove-orphans

  clean:
    desc: Remove containers and volumes for the stack
    dir: '{{.COMPOSE_DIR}}'
    cmds:
      - docker compose --profile app down --volumes --remove-orphans

  migrate:
    desc: Run backend and web database migrations
    cmds:
      - task: _ensure-db
      - task: _migrate-web
      - task: _migrate-backend

  _ensure-db:
    internal: true
    dir: '{{.COMPOSE_DIR}}'
    cmds:
      - docker compose up -d --wait timescaledb

  _migrate-backend:
    internal: true
    dir: '{{.COMPOSE_DIR}}'
    cmds:
      - docker compose run --rm migrate-up

  _migrate-web:
    internal: true
    dir: '{{.WEB_DIR}}'
    env:
      DATABASE_URL: '{{.DATABASE_URL}}'
    cmds:
      - echo "y" | npm run auth:migrate
