name: Docker Publish
description: Login to GHCR and build/push image
inputs:
  image:
    description: Fully qualified image name (e.g., ghcr.io/owner/repo:tag or ghcr.io/owner/name)
    required: true
  context:
    description: Build context
    required: false
    default: .
  file:
    description: Dockerfile path
    required: true
  tag:
    description: Tag to push (if image input omits tag)
    required: false
runs:
  using: composite
  steps:
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        push: true
        tags: ${{ inputs.tag && format('{0}:{1}', inputs.image, inputs.tag) || inputs.image }}

