// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type AppActiveJob struct {
	RunID          string         `json:"run_id"`
	MonitorID      string         `json:"monitor_id"`
	Region         string         `json:"region"`
	Status         string         `json:"status"`
	ScheduledAt    time.Time      `json:"scheduled_at"`
	LeaseExpiresAt sql.NullTime   `json:"lease_expires_at"`
	WorkerID       sql.NullString `json:"worker_id"`
	CreatedAt      time.Time      `json:"created_at"`
	DeletedAt      sql.NullTime   `json:"deleted_at"`
}

type AppActiveMonitor struct {
	ID              string                `json:"id"`
	Url             string                `json:"url"`
	IntervalMs      int32                 `json:"interval_ms"`
	TimeoutMs       int32                 `json:"timeout_ms"`
	Regions         []string              `json:"regions"`
	JitterSeed      int32                 `json:"jitter_seed"`
	RateLimitKey    sql.NullString        `json:"rate_limit_key"`
	Method          string                `json:"method"`
	Headers         pqtype.NullRawMessage `json:"headers"`
	Assertions      pqtype.NullRawMessage `json:"assertions"`
	Enabled         sql.NullBool          `json:"enabled"`
	LastScheduledAt sql.NullTime          `json:"last_scheduled_at"`
	NextDueAt       sql.NullTime          `json:"next_due_at"`
	UserID          sql.NullString        `json:"user_id"`
	CreatedAt       time.Time             `json:"created_at"`
	UpdatedAt       time.Time             `json:"updated_at"`
	Name            string                `json:"name"`
	DeletedAt       sql.NullTime          `json:"deleted_at"`
}

type AppJob struct {
	RunID          string         `json:"run_id"`
	MonitorID      string         `json:"monitor_id"`
	Region         string         `json:"region"`
	Status         string         `json:"status"`
	ScheduledAt    time.Time      `json:"scheduled_at"`
	LeaseExpiresAt sql.NullTime   `json:"lease_expires_at"`
	WorkerID       sql.NullString `json:"worker_id"`
	CreatedAt      time.Time      `json:"created_at"`
	DeletedAt      sql.NullTime   `json:"deleted_at"`
}

type AppMonitor struct {
	ID              string                `json:"id"`
	Url             string                `json:"url"`
	IntervalMs      int32                 `json:"interval_ms"`
	TimeoutMs       int32                 `json:"timeout_ms"`
	Regions         []string              `json:"regions"`
	JitterSeed      int32                 `json:"jitter_seed"`
	RateLimitKey    sql.NullString        `json:"rate_limit_key"`
	Method          string                `json:"method"`
	Headers         pqtype.NullRawMessage `json:"headers"`
	Assertions      pqtype.NullRawMessage `json:"assertions"`
	Enabled         sql.NullBool          `json:"enabled"`
	LastScheduledAt sql.NullTime          `json:"last_scheduled_at"`
	NextDueAt       sql.NullTime          `json:"next_due_at"`
	UserID          sql.NullString        `json:"user_id"`
	CreatedAt       time.Time             `json:"created_at"`
	UpdatedAt       time.Time             `json:"updated_at"`
	Name            string                `json:"name"`
	DeletedAt       sql.NullTime          `json:"deleted_at"`
}

type AppWorker struct {
	ID                   string         `json:"id"`
	Region               string         `json:"region"`
	Version              string         `json:"version"`
	LastSeenAt           time.Time      `json:"last_seen_at"`
	RegisteredAt         time.Time      `json:"registered_at"`
	Status               string         `json:"status"`
	Hostname             sql.NullString `json:"hostname"`
	EnrolledAt           time.Time      `json:"enrolled_at"`
	CertificateExpiresAt sql.NullTime   `json:"certificate_expires_at"`
	RevokedAt            sql.NullTime   `json:"revoked_at"`
	RevokedReason        sql.NullString `json:"revoked_reason"`
}

type AppWorkerCapability struct {
	WorkerID        string `json:"worker_id"`
	CapabilityKey   string `json:"capability_key"`
	CapabilityValue string `json:"capability_value"`
}

type TsResultsAgg1d struct {
	MonitorID        string      `json:"monitor_id"`
	Region           string      `json:"region"`
	Bucket           interface{} `json:"bucket"`
	TotalChecks      int64       `json:"total_checks"`
	SuccessfulChecks int64       `json:"successful_checks"`
	FailedChecks     int64       `json:"failed_checks"`
	UptimePercentage int32       `json:"uptime_percentage"`
	P50Ms            float64     `json:"p50_ms"`
	P95Ms            float64     `json:"p95_ms"`
	P99Ms            float64     `json:"p99_ms"`
	MinMs            interface{} `json:"min_ms"`
	MaxMs            interface{} `json:"max_ms"`
	AvgMs            float64     `json:"avg_ms"`
}

type TsResultsAgg1h struct {
	MonitorID        string      `json:"monitor_id"`
	Region           string      `json:"region"`
	Bucket           interface{} `json:"bucket"`
	TotalChecks      int64       `json:"total_checks"`
	SuccessfulChecks int64       `json:"successful_checks"`
	FailedChecks     int64       `json:"failed_checks"`
	UptimePercentage int32       `json:"uptime_percentage"`
	P50Ms            float64     `json:"p50_ms"`
	P95Ms            float64     `json:"p95_ms"`
	P99Ms            float64     `json:"p99_ms"`
	MinMs            interface{} `json:"min_ms"`
	MaxMs            interface{} `json:"max_ms"`
	AvgMs            float64     `json:"avg_ms"`
}

type TsResultsAgg1m struct {
	MonitorID  string      `json:"monitor_id"`
	Region     string      `json:"region"`
	Bucket     interface{} `json:"bucket"`
	Count      int64       `json:"count"`
	ErrorCount int64       `json:"error_count"`
	ErrorRate  int32       `json:"error_rate"`
	P50Ms      float64     `json:"p50_ms"`
	P95Ms      float64     `json:"p95_ms"`
	P99Ms      float64     `json:"p99_ms"`
	MinMs      interface{} `json:"min_ms"`
	MaxMs      interface{} `json:"max_ms"`
	AvgMs      float64     `json:"avg_ms"`
}

type TsResultsRaw struct {
	RunID        string         `json:"run_id"`
	MonitorID    string         `json:"monitor_id"`
	Region       string         `json:"region"`
	EventAt      time.Time      `json:"event_at"`
	Status       string         `json:"status"`
	HttpCode     sql.NullInt32  `json:"http_code"`
	DnsMs        sql.NullInt32  `json:"dns_ms"`
	ConnectMs    sql.NullInt32  `json:"connect_ms"`
	TlsMs        sql.NullInt32  `json:"tls_ms"`
	TtfbMs       sql.NullInt32  `json:"ttfb_ms"`
	DownloadMs   sql.NullInt32  `json:"download_ms"`
	TotalMs      sql.NullInt32  `json:"total_ms"`
	SizeBytes    sql.NullInt64  `json:"size_bytes"`
	ErrorMessage sql.NullString `json:"error_message"`
}
